# Generated by Django 3.2.7 on 2021-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('release_date', models.CharField(max_length=30)),
                ('lte_exists', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
